baseURL = "https://www.sezginege.com"
title = "Hi, I am Sezgin!"
languageCode = "en"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = "sezginege-com"
googleAnalytics = "UA-53768957-1"

Paginate = 20
# paginatePath  ="blog"
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.rss]
excludePageTypes = ["page"]

[Author]
name = "Sezgin Ege"
email = "mail@sezginege.com"

[params.info]
description = ""
title404 = "Content most probably has been moved"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Sezgin Ege"
startYear = "2018"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#ffcd00"
hideMainMenu = false
rtl = false

[params.sidebar]
enable = false

[params.widgets]
header = []
homepage = ["recent_posts"]
sidebar = ["about","search","sidebar_menu","taxonomy_cloud"]
footer = ["social_menu"]

[params.opengraph.facebook]
admins = [1650110188] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "SezginEge" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
twitter = "SezginEge"
linkedin = "sezginege"
email = "mail@sezginege.com"
github = "SezginEge"
facebook = ""
instagram = "SezginEge"
telegram = "SezginEge"
codepen = ""
gitlab = ""
google_scholar = ""
youtube = ""

[params.comments]
enable = true

# Isso: https://posativ.org/isso/
[params.comments.isso]
enable = false
scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[params.comments.staticman]
enable = false
apiEndpoint = "https://api.staticman.net/v2/entry"
maxDepth = 2
username = "SezginEge"
repository = "minimo"

# Utterances: https://utteranc.es
[params.comments.utterances]
enable = false
issueTerm = "pathname" # pathname / url / title

[params.comments.utterances.github]
username = "SezginEge"
repository = "sezginege.com"

[params.search]
client = "fuse" # algolia / fuse / lunr

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[taxonomies]
# author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
# blog = ":filename/"
# page = ":filename/"


[[menu.main]]
name = "/home/sezginege"
weight = -30	
identifier = "/"
url = "/"

[[menu.main]]
name = "subscribe"
weight = -20	
identifier = "/index.xml"
url = "/index.xml"

[blackfriday]
hrefTargetBlank = true

[languages]
[languages.en]
lang = "en"
languageName = "English"
weight = 1
